dist: xenial

sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failure:
    - rust: nightly

cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force
  fi
before_install:
  - set -e
  - rustup self update

install:
  - echo "apt installs"
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install libssl-dev pkg-config cmake zip g++ zlib1g-dev python python-dev python-pip unzip curl libcurl3-gnutls openjdk-8-jdk
  - echo "apt installs done"
  - echo "installing clippy"
  - rustup component add clippy
  - echo "clippy installed"
  - echo "installing bazel"
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install bazel
  - echo "bazel installed"
  - echo "installing tensorflow python dependencies"
  - pip install -U --user pip six numpy wheel setuptools mock
  - pip install -U --user keras_applications==1.0.6 --no-deps
  - pip install -U --user keras_preprocessing==1.0.5 --no-deps
  - echo "tensorflow python dependencies installed"

script:
  - cargo clean
  - cargo build --verbose
  - cargo clippy --verbose
  - cargo test --verbose

after_script:
  - set +e

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
notifications:
  email:
on_success: never
